# Generated by Django 4.1.2 on 2022-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('seller', models.CharField(max_length=30)),
            ],
        ),
    ]
